// <auto-generated />
using Lexikar.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lexikar.Migrations
{
    [DbContext(typeof(DictionaryContext))]
    [Migration("20210811110630_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lexikar.Models.CorpusFile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CloneID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CorpusFiles");
                });

            modelBuilder.Entity("Lexikar.Models.CorpusSource", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CloneID")
                        .HasColumnType("int");

                    b.Property<int>("FileSourceID")
                        .HasColumnType("int");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<string>("TextRow")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("FileSourceID");

                    b.ToTable("CorpusSources");
                });

            modelBuilder.Entity("Lexikar.Models.DescText", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CloneID")
                        .HasColumnType("int");

                    b.Property<string>("text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("what")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DescTexts");
                });

            modelBuilder.Entity("Lexikar.Models.Translation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CloneID")
                        .HasColumnType("int");

                    b.Property<string>("FR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nezamnenovat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Nom")
                        .HasColumnType("bit");

                    b.Property<bool>("Ost")
                        .HasColumnType("bit");

                    b.Property<string>("Poznamka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Systematika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verb")
                        .HasColumnType("bit");

                    b.Property<string>("Zdroj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("Lexikar.Models.CorpusSource", b =>
                {
                    b.HasOne("Lexikar.Models.CorpusFile", "CorpusFile")
                        .WithMany("CorpusSources")
                        .HasForeignKey("FileSourceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
